#!/usr/bin/env python3
"""Export an IRext SQLite index and binary pack as an offline catalog.

The generated catalog keeps every category and brand, orders codes by the
database priority, and stores duplicate binary payloads only once. It is safe
to rerun when either the SQLite index or the binary pack is updated.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sqlite3
from collections import defaultdict
from pathlib import Path
from typing import Any


def normalize_chinese(value: str | None) -> str | None:
    """Repair UTF-8 database text that SQLite exposed through the GBK code page."""
    if value is None:
        return None
    try:
        return value.encode("gbk").decode("utf-8")
    except UnicodeError:
        return value


def inspect_database(database: Path) -> None:
    with sqlite3.connect(database) as connection:
        tables = connection.execute(
            "SELECT name, sql FROM sqlite_master WHERE type = 'table' ORDER BY name"
        ).fetchall()
        for name, schema in tables:
            print(f"\n[{name}]")
            print(schema)
            columns = connection.execute(f'PRAGMA table_info("{name}")').fetchall()
            print("columns:", ", ".join(column[1] for column in columns))
            print("rows:", connection.execute(f'SELECT COUNT(*) FROM "{name}"').fetchone()[0])


def print_summary(database: Path, sample_category: int = 1) -> None:
    with sqlite3.connect(database) as connection:
        print("categories:")
        for row in connection.execute(
            """
            SELECT category_id, category_name, COUNT(*)
            FROM remote_index
            WHERE status = 1
            GROUP BY category_id, category_name
            ORDER BY category_id
            """
        ):
            print(*row, sep="\t")

        print(f"\nCategory {sample_category} samples:")
        for row in connection.execute(
            """
            SELECT category_id, category_name, brand_id, brand_name, remote, sub_cate, priority,
                   remote_number, binary_md5
            FROM remote_index
            WHERE category_id = ? AND status = 1
            ORDER BY brand_name, priority DESC, id
            LIMIT 30
            """,
            (sample_category,),
        ):
            print(*row, sep="\t")


def index_binaries(binary_dir: Path) -> dict[str, Any]:
    control_code_paths: dict[str, list[Path]] = defaultdict(list)
    for path in binary_dir.glob("*.bin"):
        if path.name.startswith("irda_new_ac_"):
            control_code = path.stem.rsplit("_", 1)[-1]
        elif "_remote_" in path.stem:
            control_code = path.stem[path.stem.index("_remote_") + 1 :]
        else:
            continue
        control_code_paths[control_code].append(path)
    return {"control_code_paths": control_code_paths}


def load_records(database: Path) -> list[dict[str, Any]]:
    query = """
        SELECT ri.id, ri.category_id, ri.category_name, c.name_en AS category_name_en,
               ri.brand_id, ri.brand_name, b.name_en AS brand_name_en,
               ri.protocol, ri.remote, ri.remote_map, ri.sub_cate, ri.priority,
               ri.remote_number, ri.binary_md5,
               COALESCE(b.priority, 0) AS brand_priority
        FROM remote_index AS ri
        LEFT JOIN category AS c ON c.id = ri.category_id
        LEFT JOIN brand AS b ON b.id = ri.brand_id AND b.category_id = ri.category_id
        WHERE ri.status = 1 AND ri.remote IS NOT NULL AND ri.remote != ''
        ORDER BY ri.category_id, brand_priority DESC, ri.brand_name,
                 ri.priority DESC, ri.id
    """
    with sqlite3.connect(database) as connection:
        connection.row_factory = sqlite3.Row
        return [dict(row) for row in connection.execute(query)]


def binary_for_record(record: dict[str, Any], indexed_binaries: dict[str, Any]) -> Path | None:
    matched = indexed_binaries["control_code_paths"].get(str(record["remote"]), [])
    if len(matched) == 1:
        return matched[0]
    if len(matched) > 1:
        protocol = (record["protocol"] or "").lower()
        protocol_matches = [path for path in matched if protocol and protocol in path.name.lower()]
        if len(protocol_matches) == 1:
            return protocol_matches[0]
    return None


def emit_catalog_header(path: Path, catalog: bytes, binaries: list[dict[str, Any]]) -> None:
    lines = [
        "// Generated by tools/export_irext_catalog.py. Do not edit manually.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "namespace irext_catalog {",
        "",
        "struct BinaryDescriptor {",
        "  uint32_t offset;",
        "  uint16_t length;",
        "  uint8_t category_id;",
        "  uint8_t subcategory;",
        "};",
        "",
        "static const uint8_t data[] PROGMEM = {",
    ]
    if catalog:
        for offset in range(0, len(catalog), 16):
            values = ", ".join(f"0x{value:02X}" for value in catalog[offset : offset + 16])
            lines.append(f"  {values},")
    else:
        lines.append("  0x00,")
    lines.extend(["};", "", "static const BinaryDescriptor binaries[] PROGMEM = {"])
    for binary in binaries:
        lines.append(
            "  {"
            f"{binary['offset']}UL, {binary['length']}, {binary['category_id']}, "
            f"{binary['subcategory']}"
            "},"
        )
    lines.extend(
        [
            "};",
            "",
            f"static constexpr size_t data_size = {len(catalog)};",
            f"static constexpr size_t binary_count = {len(binaries)};",
            "",
            "}  // namespace irext_catalog",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="ascii")


def emit_catalog_index_header(
    path: Path, categories: list[dict[str, Any]], binaries: list[dict[str, Any]]
) -> None:
    def cpp_string(value: str) -> str:
        return value.replace("\\", "\\\\").replace('"', '\\"')

    binary_by_id = {binary["id"]: binary for binary in binaries}
    brands: list[tuple[int, str, str | None]] = []
    entries: list[tuple[int, str, int, int]] = []
    for type_index, category in enumerate(categories):
        for brand in category["brands"]:
            brand_index = len(brands)
            brands.append((type_index, brand["name"] or "", brand["name_cn"]))
            for code in brand["codes"]:
                binary = binary_by_id.get(code["binary_id"])
                if binary is not None:
                    entries.append(
                        (brand_index, str(code["control_code"]), binary["offset"], binary["length"])
                    )

    lines = [
        "// Generated by tools/export_irext_catalog.py. Do not edit manually.",
        "#pragma once",
        "",
        "#include <Arduino.h>",
        "",
        "namespace irext_catalog {",
        "",
        "struct TypeEntry { const char *name; };",
        "struct BrandEntry { uint8_t type_index; const char *name; };",
        "struct ControlCodeEntry { uint16_t brand_index; const char *code; uint32_t offset; uint16_t length; };",
        "",
        "static const TypeEntry types[] PROGMEM = {",
    ]
    for category in categories:
        lines.append(f'  {{"{cpp_string(category["name_cn"] or category["name"])}"}},')
    lines.extend(["};", "", "static const BrandEntry brands[] PROGMEM = {"])
    for type_index, brand_name, brand_name_cn in brands:
        label = brand_name_cn or brand_name
        lines.append(f'  {{{type_index}, "{cpp_string(label)}"}},')
    lines.extend(["};", "", "static const ControlCodeEntry control_codes[] PROGMEM = {"])
    for brand_index, code, offset, length in entries:
        lines.append(f'  {{{brand_index}, "{cpp_string(code)}", {offset}UL, {length}}},')
    lines.extend(
        [
            "};",
            "",
            f"static constexpr size_t type_count = {len(categories)};",
            f"static constexpr size_t brand_count = {len(brands)};",
            f"static constexpr size_t control_code_count = {len(entries)};",
            "",
            "}  // namespace irext_catalog",
            "",
        ]
    )
    path.write_text("\n".join(lines), encoding="utf-8")


def export_catalog(
    database: Path,
    binary_dir: Path | None,
    output_dir: Path,
    debug_dir: Path | None,
    allow_missing: bool,
    emit_header: bool,
) -> None:
    records = load_records(database)
    indexed_binaries = index_binaries(binary_dir) if binary_dir is not None else {}
    payloads: dict[str, dict[str, Any]] = {}
    missing: list[dict[str, Any]] = []

    for record in records:
        binary_path = binary_for_record(record, indexed_binaries)
        if binary_path is None:
            missing.append(record)
            record["binary_id"] = None
            continue
        content = binary_path.read_bytes()
        digest = hashlib.sha256(content).hexdigest()
        payload = payloads.setdefault(
            digest,
            {
                "sha256": digest,
                "filename": binary_path.name,
                "category_id": record["category_id"],
                "subcategory": record["sub_cate"],
                "content": content,
            },
        )
        record["binary_id"] = digest
        record["binary_filename"] = payload["filename"]

    if missing and not allow_missing:
        raise RuntimeError(
            f"{len(missing)} active index records have no matching bin file. "
            "Restore the matching pack or rerun with --allow-missing."
        )

    ordered_payloads = sorted(
        payloads.values(), key=lambda payload: (payload["category_id"], payload["filename"])
    )
    catalog = bytearray()
    binary_descriptors: list[dict[str, Any]] = []
    for binary_id, payload in enumerate(ordered_payloads):
        payload["offset"] = len(catalog)
        payload["length"] = len(payload["content"])
        payload["id"] = binary_id
        catalog.extend(payload["content"])
        binary_descriptors.append(
            {
                "id": binary_id,
                "filename": payload["filename"],
                "offset": payload["offset"],
                "length": payload["length"],
                "category_id": payload["category_id"],
                "subcategory": payload["subcategory"],
                "sha256": payload["sha256"],
            }
        )

    id_by_digest = {payload["sha256"]: payload["id"] for payload in ordered_payloads}
    categories: dict[tuple[int, str], dict[str, Any]] = {}
    brands: dict[tuple[int, int | None, str], dict[str, Any]] = {}
    for record in records:
        category_name_cn = normalize_chinese(record["category_name"])
        category_name = record["category_name_en"] or f"type-{record['category_id']}"
        category_key = (record["category_id"], category_name)
        category = categories.setdefault(
            category_key,
            {
                "id": record["category_id"],
                "name": category_name,
                "name_cn": category_name_cn,
                "brands": [],
            },
        )
        brand_key = (record["category_id"], record["brand_id"], record["brand_name"])
        brand = brands.get(brand_key)
        if brand is None:
            brand = {
                "id": record["brand_id"],
                "name": record["brand_name_en"] or f"brand-{record['brand_id']}",
                "name_cn": normalize_chinese(record["brand_name"]),
                "priority": record["brand_priority"],
                "codes": [],
            }
            brands[brand_key] = brand
            category["brands"].append(brand)
        code = {
            "remote_index_id": record["id"],
            "model": record["remote_map"] or record["remote_number"],
            "control_code": record["remote"],
            "protocol": record["protocol"],
            "sub_category": record["sub_cate"],
            "priority": record["priority"],
            "binary_id": id_by_digest.get(record["binary_id"]),
        }
        brand["codes"].append(code)

    category_list = sorted(categories.values(), key=lambda category: category["id"])
    for category in category_list:
        category["brands"].sort(
            key=lambda brand: (-brand["priority"], brand["name"] or "", brand["id"] or 0)
        )
        for brand in category["brands"]:
            brand["codes"].sort(
                key=lambda code: (-code["priority"], code["remote_index_id"])
            )

    manifest = {
        "format": 1,
        "database": database.name,
        "binary_directory": binary_dir.name if binary_dir is not None else None,
        "categories": category_list,
        "binaries": binary_descriptors,
        "report": {
            "active_remote_indexes": len(records),
            "unique_binaries": len(binary_descriptors),
            "binary_bytes": len(catalog),
            "missing_records": len(missing),
        },
    }
    if emit_header:
        output_dir.mkdir(parents=True, exist_ok=True)
        emit_catalog_header(output_dir / "catalog_data.h", bytes(catalog), binary_descriptors)
        emit_catalog_index_header(output_dir / "catalog_index.h", category_list, binary_descriptors)

    if debug_dir is not None:
        debug_dir.mkdir(parents=True, exist_ok=True)
        (debug_dir / "catalog.json").write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
        (debug_dir / "catalog.bin").write_bytes(catalog)
        (debug_dir / "missing_records.json").write_text(
            json.dumps(missing, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )

    print(json.dumps(manifest["report"], ensure_ascii=False))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("database", type=Path)
    parser.add_argument("--inspect", action="store_true")
    parser.add_argument("--summary", action="store_true")
    parser.add_argument("--sample-category", type=int, default=1)
    parser.add_argument("--binary-dir", type=Path)
    parser.add_argument("--output-dir", type=Path)
    parser.add_argument("--debug-dir", type=Path)
    parser.add_argument("--allow-missing", action="store_true")
    parser.add_argument("--emit-header", action="store_true")
    args = parser.parse_args()

    if args.inspect:
        inspect_database(args.database)
        return
    if args.summary:
        print_summary(args.database, args.sample_category)
        return
    if args.output_dir is None:
        parser.error("--output-dir is required for export")

    export_catalog(
        args.database,
        args.binary_dir,
        args.output_dir,
        args.debug_dir,
        args.allow_missing,
        args.emit_header,
    )


if __name__ == "__main__":
    main()
